"""empty message

Revision ID: 76dce213f0d8
Revises: b40eabad4323
Create Date: 2020-03-12 01:52:44.937159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dce213f0d8'
down_revision = 'b40eabad4323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img_info',
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('img_create_time', sa.DateTime(), nullable=True),
    sa.Column('img_delete_time', sa.DateTime(), nullable=True),
    sa.Column('img_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user_login.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('img_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img_info')
    # ### end Alembic commands ###
