"""empty message

Revision ID: b40eabad4323
Revises: 9b36d8cf913b
Create Date: 2020-03-08 18:46:20.093285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40eabad4323'
down_revision = '9b36d8cf913b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_activity', sa.Column('logout_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_activity', 'logout_time')
    # ### end Alembic commands ###
