"""empty message

Revision ID: d3b22156d0b5
Revises: fbae8ce4e831
Create Date: 2020-03-17 04:56:48.721420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b22156d0b5'
down_revision = 'fbae8ce4e831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'img_info', ['img_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'img_info', type_='unique')
    # ### end Alembic commands ###
