"""empty message

Revision ID: fbae8ce4e831
Revises: 76dce213f0d8
Create Date: 2020-03-14 08:53:31.159286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbae8ce4e831'
down_revision = '76dce213f0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('img_info_user_name_key', 'img_info', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('img_info_user_name_key', 'img_info', ['user_name'])
    # ### end Alembic commands ###
